### ISSUE TITLE
Fatal Error in Freemius SDK when NotificationX is active

### ISSUE THREAD

**Issue by imtiazrayhan** [WPDevelopers/notificationx#44]
Hi,

Love the plugin. I am using the plugin to show sales notification from Freemius. 

I just found one issue. When NotificationX is active, the Freemius SDK gives a Fatal Error. 

**Fatal error:** Cannot make non static method Freemius_Api_Base::Test() static in class Freemius_Api_WordPress in **public_html/wp-content/plugins/wp-coupons-and-deals-premium/includes/sdk/freemius/includes/sdk/FreemiusWordPress.php** on line 0

Deactivating NotificationX fixes the issue.

Regards.

**Comment by priyomukul** [comment]
Hi,

Seems like there is multiple things going on, with the same SDK. Thanks for sharing the issue. 

Regards.

**Comment by rupok** [comment]
@imtiazrayhan Issue has been addressed and fixed. Please update both of your NotificationX plugin.

**Comment by imtiazrayhan** [comment]
@rupok thanks for the update. I got update for the free version(1.1.2) only. Pro version still not showing any available updates.

**Comment by rupok** [comment]
@imtiazrayhan 
Would you kindly download from your account(https://wpdeveloper.net/account/) for now and update manually? We have improved the updater from v1.0.1 but you might be using v1.0.0.
